// ── Single source of truth for all trip data ──────────────────────────────────
// To add a new trip: add an entry here. No other files need changing.

export const tripsData = [
  {
    // ── Meta (used in cards, SEO, booking form) ──────────────────────────────
    id: 1,
    slug: 'diu',
    name: 'Diu, India',
    tagline: 'Portuguese History Meets Golden Coastlines',
    location: 'Diu, Gujarat, India',
    emoji: '🏖️',
    duration: '1 Night · 2 Days',
    dates: 'Apr–Jun 2026 · Weekends',
    price: 3099,
    oldPrice: 3499,
    spotsTotal: 10,
    badge: '🎉 Launch Price',
    accentColor: 'coral',           // used for theme: coral | amber | teal
    heroImage: 'https://images.pexels.com/photos/3030043/pexels-photo-3030043.jpeg?auto=compress&cs=tinysrgb&w=1400',
    cardImage: 'https://images.pexels.com/photos/3030043/pexels-photo-3030043.jpeg?auto=compress&cs=tinysrgb&w=600',
    highlights: ['Pristine Beaches', 'Portuguese Fort', 'Water Sports'],
    tags: ['🏖️ Beaches', '🏰 Diu Fort', '🚤 Water Sports', '🍽️ Thali', '🔥 Bonfire'],
    batches: [
      { label: 'Batch 1',  dates: 'Fri 17 Apr → Sun 19 Apr', month: 'April' },
      { label: 'Batch 2',  dates: 'Fri 24 Apr → Sun 26 Apr', month: 'April' },
      { label: 'Batch 3',  dates: 'Fri 1 May → Sun 3 May',   month: 'May'   },
      { label: 'Batch 4',  dates: 'Fri 8 May → Sun 10 May',  month: 'May'   },
      { label: 'Batch 5',  dates: 'Fri 15 May → Sun 17 May', month: 'May'   },
      { label: 'Batch 6',  dates: 'Fri 22 May → Sun 24 May', month: 'May'   },
      { label: 'Batch 7',  dates: 'Fri 29 May → Sun 31 May', month: 'May'   },
      { label: 'Batch 8',  dates: 'Fri 5 Jun → Sun 7 Jun',   month: 'June'  },
      { label: 'Batch 9',  dates: 'Fri 12 Jun → Sun 14 Jun', month: 'June'  },
      { label: 'Batch 10', dates: 'Fri 19 Jun → Sun 21 Jun', month: 'June'  },
      { label: 'Batch 11', dates: 'Fri 26 Jun → Sun 28 Jun', month: 'June'  },
    ],

    // ── Trip page content ────────────────────────────────────────────────────
    description: 'Experience the magic of Diu, where Portuguese history meets golden coastlines. From the imposing walls of the Diu Fort to the serene shores of Nagoa Beach, this weekend getaway is designed for deep relaxation and meaningful group bonding. Escape the hustle and join our founding batch for an unforgettable island adventure.',
    highlightCards: [
      { emoji: '🏖️', label: 'Nagoa Beach',       sub: 'Beach & water sports' },
      { emoji: '🏰', label: 'Diu Fort',           sub: 'Portuguese heritage'  },
      { emoji: '🌅', label: 'Jallandhar Beach',   sub: 'Sunset bonfire night' },
      { emoji: '⛪', label: "St. Paul's Church",  sub: 'Colonial architecture'},
      { emoji: '🌊', label: 'Chakratirth Beach',  sub: 'Sunrise walk'         },
      { emoji: '🍽️', label: 'Gujarati Thali',     sub: 'Local cuisine'        },
    ],
    inclusionIcons: [
      { label: 'AC Transport', desc: 'Pick & Drop',      icon: 'Car'    },
      { label: 'Luxury Stay',  desc: 'Verified Hotels',  icon: 'Shield' },
      { label: 'All Meals',    desc: 'B/L/D Included',   icon: 'Coffee' },
      { label: 'Activities',   desc: 'Entry Fees',       icon: 'Zap'    },
    ],
    inclusions: [
      'AC Tempo Traveller (round trip)',
      '1 night hotel stay (twin sharing)',
      '4 meals — lunch, dinner, breakfast, lunch',
      'Travel coordinator throughout',
      'First aid & emergency support',
    ],
    exclusions: [
      'Personal expenses & shopping',
      'Extra water sports beyond package',
      'Any activity not in itinerary',
    ],
    itinerary: [
      {
        day: 'Day 1', label: 'Arrival & Beach Bliss', iconKey: 'Sunrise', color: 'bg-coral-500',
        timeline: [
          { time: '08:00 AM', activity: 'Group assembly & departure from meeting point' },
          { time: '12:00 PM', activity: 'Arrive in Diu — check-in to beachside hotel' },
          { time: '01:30 PM', activity: 'Welcome lunch at a local restaurant' },
          { time: '03:30 PM', activity: 'Nagoa Beach — swim, sunbathe & water sports (jet ski, banana boat)' },
          { time: '06:30 PM', activity: 'Sunset walk at Diu Fort & Portuguese architecture tour' },
          { time: '08:30 PM', activity: 'Group dinner at Jallandhar Beach — bonfire & music night' },
        ]
      },
      {
        day: 'Day 2', label: 'Explore, Eat & Head Home', iconKey: 'Sunset', color: 'bg-orange-500',
        timeline: [
          { time: '07:00 AM', activity: 'Early morning sunrise walk at Chakratirth Beach' },
          { time: '08:30 AM', activity: 'Breakfast at hotel' },
          { time: '10:00 AM', activity: "Visit St. Paul's Church & Diu Museum" },
          { time: '11:30 AM', activity: 'Ghoghla Beach — last dip & group photos' },
          { time: '01:00 PM', activity: 'Farewell lunch — local Gujarati thali' },
          { time: '03:00 PM', activity: 'Departure & drop-off at meeting point' },
        ]
      }
    ],
    photos: [
      'https://images.pexels.com/photos/3030016/pexels-photo-3030016.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/3030043/pexels-photo-3030043.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/14123793/pexels-photo-14123793.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/18124555/pexels-photo-18124555.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/15921672/pexels-photo-15921672.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/744481/pexels-photo-744481.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    meetingPoint: {
      title: 'Meeting Point',
      lines: [
        { bold: 'Departure:', text: 'Friday night ~3:00 AM — exact location shared on WhatsApp group after booking confirmation.' },
      ],
      note: '📍 Typically a central pickup point in your city. We\'ll confirm 48 hours before departure.',
    },
    whatToCarry: [
      { emoji: '🪪', text: 'Government photo ID (Aadhaar / Passport)' },
      { emoji: '👙', text: 'Swimwear & extra set of clothes' },
      { emoji: '🧴', text: 'Sunscreen, sunglasses & hat' },
      { emoji: '👟', text: 'Comfortable footwear & flip flops' },
      { emoji: '💊', text: 'Personal medicines if any' },
      { emoji: '🔋', text: 'Power bank & phone charger' },
      { emoji: '💵', text: 'Cash for personal expenses & water sports' },
      { emoji: '🎒', text: 'Small backpack — travel light!' },
    ],
    faqs: [
      { q: 'Can I join solo?', a: "Absolutely! Most of our travelers come solo. You'll be grouped with like-minded people and won't feel out of place at all." },
      { q: 'Is it safe for solo women travelers?', a: 'Yes. We have a dedicated trip coordinator throughout and maintain a safe, respectful group environment.' },
      { q: 'When do I pay?', a: "No payment needed right now. Once we confirm your spot via WhatsApp/call, we'll share payment details. Full payment before departure." },
      { q: 'What if the trip gets cancelled?', a: 'If we cancel due to insufficient group size or any unforeseen reason, you get a full refund within 5–7 business days.' },
      { q: 'Are water sports included?', a: 'Basic beach activities are included. Jet ski, banana boat, and other paid water sports are optional and paid on the spot.' },
      { q: 'Are seats limited?', a: 'Yes — seats are limited per batch to keep the experience personal and high-quality. Book early to secure your spot.' },
    ],
    bookingCardInfo: [
      { label: 'Upcoming Batches', value: 'Every Weekend'    },
      { label: 'Seats',             value: '🔥 Limited'      },
      { label: 'Pickup Point',     value: 'Central Location' },
      { label: 'Status',           value: '🔥 Filling Fast!' },
    ],
    bookingCardBadge: '🎉 Launch Deal',
    bookingCardSaveText: 'SAVE ₹400',
    bookingCardQuote: 'All inclusive: Transport, stay, meals & activities.',
    tagline: null,
  },

  // ────────────────────────────────────────────────────────────────────────────
  {
    id: 2,
    slug: 'dwarka',
    name: 'Dwarka, Gujarat',
    tagline: 'Spirituality Meets the Sea',
    location: 'Devbhumi Dwarka, Gujarat, India',
    emoji: '🛕',
    duration: '2 Nights · 3 Days',
    dates: 'Apr–Jun 2026 · Thu–Mon',
    price: 4999,
    oldPrice: null,
    spotsTotal: 10,
    badge: '🆕 New Trip',
    accentColor: 'amber',
    heroImage: 'https://images.pexels.com/photos/32604468/pexels-photo-32604468.jpeg?auto=compress&cs=tinysrgb&w=1400',
    cardImage: 'https://images.pexels.com/photos/32604468/pexels-photo-32604468.jpeg?auto=compress&cs=tinysrgb&w=600',
    highlights: ['Dwarkadhish Temple', 'Beyt Dwarka', 'Sunset Point'],
    tags: ['🛕 Dwarkadhish', '🏝️ Beyt Dwarka', '🌅 Sunset Point', '🐚 Beach', '🍽️ Thali'],
    batches: [
      { label: 'Batch 1',  dates: 'Thu 17 Apr → Mon 21 Apr', month: 'April' },
      { label: 'Batch 2',  dates: 'Thu 24 Apr → Mon 28 Apr', month: 'April' },
      { label: 'Batch 3',  dates: 'Thu 1 May → Mon 5 May',   month: 'May'   },
      { label: 'Batch 4',  dates: 'Thu 8 May → Mon 12 May',  month: 'May'   },
      { label: 'Batch 5',  dates: 'Thu 15 May → Mon 19 May', month: 'May'   },
      { label: 'Batch 6',  dates: 'Thu 22 May → Mon 26 May', month: 'May'   },
      { label: 'Batch 7',  dates: 'Thu 29 May → Mon 2 Jun',  month: 'May'   },
      { label: 'Batch 8',  dates: 'Thu 5 Jun → Mon 9 Jun',   month: 'June'  },
      { label: 'Batch 9',  dates: 'Thu 12 Jun → Mon 16 Jun', month: 'June'  },
      { label: 'Batch 10', dates: 'Thu 19 Jun → Mon 23 Jun', month: 'June'  },
      { label: 'Batch 11', dates: 'Thu 26 Jun → Mon 30 Jun', month: 'June'  },
    ],
    description: 'Step into the sacred city of Dwarka — one of the four holy dhams of India and a place where spirituality meets the sea. Known for the magnificent Dwarkadhish Temple, the serene Gomti Ghat, and the island paradise of Beyt Dwarka, this weekend trip is a perfect blend of devotion, heritage, and coastal beauty. Join your crew for a soulful escape that\'s unlike any other.',
    highlightCards: [
      { emoji: '🛕', label: 'Dwarkadhish Temple', sub: 'Guided heritage walk'   },
      { emoji: '🏝️', label: 'Beyt Dwarka',        sub: 'Island adventure'       },
      { emoji: '🌅', label: 'Gomti Ghat Aarti',   sub: 'Sunrise spiritual start'},
      { emoji: '🐬', label: 'Dolphin Spotting',   sub: 'Marine excursion'       },
      { emoji: '🔱', label: 'Nageshwar Jyotirlinga', sub: '12 Jyotirlinga darshan'},
      { emoji: '🔥', label: 'Beach Bonfire',       sub: 'Music night under stars'},
    ],
    inclusionIcons: [
      { label: 'AC Transport', desc: 'Overnight Round Trip', icon: 'Car'     },
      { label: 'Hotel Stay',   desc: '2 Nights',             icon: 'Shield'  },
      { label: 'All Meals',    desc: '6 Meals Included',     icon: 'Utensils'},
      { label: 'Activities',   desc: 'Beach & Temple',       icon: 'Zap'     },
    ],
    inclusions: [
      'AC Tempo Traveller — overnight round trip',
      '2 nights hotel stay (twin sharing)',
      '6 meals — breakfast, lunch & dinner (Day 1 & Day 2)',
      'Farewell lunch on Day 3',
      'Road transfer — Okha to Beyt Dwarka & back',
      'Guided temple walk at Dwarkadhish',
      'Beach activities — volleyball, sandcastle, group games',
      'Bonfire & music night on Day 2',
      'Travel coordinator throughout the trip',
      'First aid & emergency support',
    ],
    exclusions: [
      'Water sports — jet ski, banana boat, paddleboarding (paid on spot)',
      'Snorkelling / scuba diving (paid on spot)',
      'Temple donation & prasad',
      'Personal expenses & shopping',
      'Any activity not listed in the itinerary',
    ],
    itinerary: [
      {
        day: 'Day 1 — Friday', label: 'Arrival & Temple Darshan', iconKey: 'Sunrise', color: 'bg-amber-500',
        timeline: [
          { time: '07:30 AM', activity: 'Arrive in Dwarka after overnight journey — freshen up at hotel' },
          { time: '09:00 AM', activity: 'Breakfast at hotel' },
          { time: '10:30 AM', activity: 'Dwarkadhish Temple darshan & guided heritage walk through the ancient city' },
          { time: '01:00 PM', activity: 'Lunch at local restaurant — Gujarati thali' },
          { time: '03:00 PM', activity: 'Rukmini Devi Temple & Gomti Ghat — take a holy dip' },
          { time: '05:30 PM', activity: 'Dwarka Beach — snorkelling & scuba diving (optional, paid extra)' },
          { time: '07:00 PM', activity: 'Sunset at Dwarka Lighthouse viewpoint — group photos' },
          { time: '08:30 PM', activity: 'Group dinner at local dhaba — Gujarati thali night' },
        ]
      },
      {
        day: 'Day 2 — Saturday', label: 'Beyt Dwarka Island Adventure', iconKey: 'Waves', color: 'bg-orange-500',
        timeline: [
          { time: '06:00 AM', activity: 'Gomti Ghat sunrise aarti — spiritual start to the day' },
          { time: '08:00 AM', activity: 'Breakfast at hotel' },
          { time: '09:30 AM', activity: 'Drive to Beyt Dwarka island — temple & beach time' },
          { time: '10:30 AM', activity: 'Beyt Dwarkadhish Temple darshan — one of the oldest temples in the region' },
          { time: '12:00 PM', activity: 'Beach time — jet skiing, banana boat rides, paddleboarding & dolphin spotting' },
          { time: '01:30 PM', activity: 'Beach volleyball, sandcastle building & group games on the shore' },
          { time: '03:00 PM', activity: 'Nageshwar Jyotirlinga Temple — one of the 12 Jyotirlingas of India' },
          { time: '05:00 PM', activity: 'Drive back from Beyt Dwarka — free time & shopping' },
          { time: '08:00 PM', activity: 'Beach bonfire, music & group dinner under the stars' },
        ]
      },
      {
        day: 'Day 3 — Sunday', label: 'Marine Walk & Heading Home', iconKey: 'Sunset', color: 'bg-rose-500',
        timeline: [
          { time: '07:00 AM', activity: 'Morning walk along Dwarka Beach — marine excursion & birdwatching' },
          { time: '08:30 AM', activity: 'Breakfast & hotel checkout' },
          { time: '10:00 AM', activity: 'Okha port sightseeing & last-minute shopping for local handicrafts' },
          { time: '12:30 PM', activity: 'Farewell lunch — Gujarati thali before departure' },
          { time: '02:00 PM', activity: 'Departure — overnight journey back home' },
          { time: '~8:00 AM (Mon)', activity: 'Arrive back at meeting point' },
        ]
      }
    ],
    photos: [
      'https://images.pexels.com/photos/32604468/pexels-photo-32604468.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/36530015/pexels-photo-36530015.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/23601365/pexels-photo-23601365.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/15001997/pexels-photo-15001997.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/23144483/pexels-photo-23144483.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/32664239/pexels-photo-32664239.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    meetingPoint: {
      title: 'Meeting Point',
      lines: [
        { bold: 'Departure:', text: 'Thursday night ~12:00 AM — exact location shared on WhatsApp group after booking confirmation.' },
      ],
      note: "📍 Typically a central pickup point in your city. We'll confirm 48 hours before departure.",
    },
    whatToCarry: [
      { emoji: '🪪', text: 'Government photo ID (Aadhaar / Passport)' },
      { emoji: '👕', text: '2–3 sets of comfortable clothes' },
      { emoji: '🧴', text: 'Sunscreen, sunglasses & hat' },
      { emoji: '👟', text: 'Comfortable walking footwear' },
      { emoji: '💊', text: 'Personal medicines if any' },
      { emoji: '🔋', text: 'Power bank & phone charger' },
      { emoji: '💵', text: 'Cash for water sports & personal expenses' },
      { emoji: '🎒', text: 'Small backpack — travel light!' },
    ],
    faqs: [
      { q: 'Can I join solo?', a: "Absolutely! Most of our travelers come solo. You'll be grouped with like-minded people and it's a great way to make new friends." },
      { q: 'Is it safe for solo women travelers?', a: 'Yes. We have a dedicated trip coordinator throughout and maintain a safe, respectful group environment.' },
      { q: 'When do I pay?', a: "No payment needed right now. Once we confirm your spot via WhatsApp/call, we'll share payment details. Full payment before departure." },
      { q: 'What if the trip gets cancelled?', a: 'If we cancel due to insufficient group size or any unforeseen reason, you get a full refund within 5–7 business days.' },
      { q: 'Are water sports included?', a: 'Jet ski, banana boat and paddleboarding at Beyt Dwarka are optional and paid on the spot. Beach games and bonfire are included.' },
      { q: 'Is this a religious trip?', a: "It's a mix of spiritual and leisure. Temple visits are part of the itinerary but participation is completely optional." },
    ],
    bookingCardInfo: [
      { label: 'Upcoming Batches', value: 'Weekends (Thu–Mon)' },
      { label: 'Seats',             value: '🔥 Limited'          },
      { label: 'Transport',        value: 'Premium Traveller'   },
      { label: 'Status',           value: '🔥 Selling Fast'     },
    ],
    bookingCardBadge: '✨ Featured Trip',
    bookingCardSaveText: null,
    bookingCardQuote: '2 Nights, 3 Days of spiritual bliss & coastal beauty.',
    tagline: null,
  },

  // ────────────────────────────────────────────────────────────────────────────
  {
    id: 3,
    slug: 'goa',
    name: 'Goa, India',
    tagline: 'Strangers Today, Friends Forever',
    location: 'North & South Goa, India',
    emoji: '🌴',
    duration: '3 Nights · 4 Days',
    dates: 'Wed 11 Jun → Sat 14 Jun 2026',
    price: 8999,
    oldPrice: 9999,
    spotsTotal: 12,
    badge: '🔥 Early Bird',
    accentColor: 'teal',
    heroImage: 'https://images.pexels.com/photos/994605/pexels-photo-994605.jpeg?auto=compress&cs=tinysrgb&w=1400',
    cardImage: 'https://images.pexels.com/photos/994605/pexels-photo-994605.jpeg?auto=compress&cs=tinysrgb&w=600',
    highlights: ['🛵 Scooty Included', 'Palolem Beach', 'Free Roam Day'],
    tags: ['🛵 Scooty Included', '🏖️ Palolem Beach', '🦋 Butterfly Beach', '🏰 Chapora Fort', '⛪ Bom Jesus', '🏛️ Goa Museum', '🏘️ Fontainhas', '🌊 Cola Lagoon'],
    batches: [
      { label: 'Batch 1', dates: 'Wed 11 Jun → Sat 14 Jun', month: 'June' },
    ],
    description: "Goa is not just a destination — it's a feeling. Join our Gujarat-to-Goa group trip and experience the best of both South and North Goa with a squad of strangers who will become your travel family. From the tranquil lagoons of Cola Beach and the hidden cliffs of Butterfly Beach to the iconic Chapora Fort and buzzing Baga Beach — this 4-day trip is crafted for those who want real memories, real connections, and real Goa.\n\nAnd the best part? We give you a scooty 🛵. Ride wherever you want, whenever you want. Chase that hidden beach nobody talks about, find that cafe down the lane, or just ride along the coast with the wind in your hair. No fixed agenda — just Goa the way it's meant to be felt. Free, wild, and unforgettable.",
    highlightCards: [
      { emoji: '🛵', label: 'Scooty Included',    sub: 'Ride anywhere, anytime'        },
      { emoji: '⛪', label: 'Bom Jesus Basilica', sub: 'UNESCO World Heritage Church'  },
      { emoji: '🦋', label: 'Butterfly Beach',    sub: 'Hidden boat-only paradise'     },
      { emoji: '🏰', label: 'Chapora Fort',       sub: 'Iconic "Dil Chahta Hai" views' },
      { emoji: '🏛️', label: 'Goa State Museum',   sub: 'History & Portuguese legacy'   },
      { emoji: '🏘️', label: 'Fontainhas',         sub: 'Latin Quarter & colonial lanes' },
    ],
    inclusionIcons: [
      { label: 'Sleeper Train', desc: 'Round Trip',     icon: 'Train'    },
      { label: 'Hotel Stay',    desc: '3 Nights',       icon: 'Shield'   },
      { label: 'All Meals',     desc: 'B/L/D Included', icon: 'Utensils' },
      { label: 'Scooty',        desc: 'Per Person',     icon: 'Car'      },
    ],
    inclusions: [
      'Sleeper Train Travel (round trip)',
      '3 nights hotel stay (twin sharing)',
      'All meals — breakfast, lunch & dinner daily',
      '🛵 Scooty rental included for all days (1 scooty per 2 people)',
      'Fuel covered for scooty during the trip',
      'Helmet provided for each rider',
      'Group coordinator available on WhatsApp 24/7',
      'Emergency & first aid support',
    ],
    exclusions: [
      'Water sports (jet ski, parasailing, etc.) — paid on spot',
      'Club entry & personal bar expenses',
      'Personal shopping & souvenirs',
      'Any extra personal cafe or restaurant orders',
      'Traffic fines or vehicle damage',
    ],
    itinerary: [
      {
        day: 'Day 1 — Arrival & South Goa', label: 'Hidden Beaches, Lagoons & Cabo Fort Sunset', iconKey: 'Sunrise', color: 'bg-teal-500',
        timeline: [
          { time: 'Morning',  activity: '🚂 Arrive at Madgaon Station after overnight sleeper train — freshen up at hotel & check in' },
          { time: '09:30 AM', activity: '🍳 Breakfast at hotel — group introductions, trip briefing & WhatsApp group setup' },
          { time: '10:30 AM', activity: '🛵 Scooty handover — 1 per 2 people, helmets & fuel included. Quick ride safety briefing.' },
          { time: '11:30 AM', activity: '🏖️ Palolem Beach — South Goa\'s most iconic crescent beach. Swim, sunbathe & soak it in.' },
          { time: '01:30 PM', activity: '🍽️ Lunch at a beachside shack — try Goan fish curry, prawn masala & sol kadi' },
          { time: '03:00 PM', activity: '🚤 Butterfly Beach boat trip — only reachable by boat, hidden between jungle cliffs. Absolute gem.' },
          { time: '04:30 PM', activity: '🌊 Cola Beach Lagoon — a secret freshwater lagoon meets the sea. Peaceful, uncrowded, stunning.' },
          { time: '06:00 PM', activity: '🏰 Cabo De Rama Fort — ancient Portuguese coastal fort. Best golden hour views over the Arabian Sea.' },
          { time: '08:30 PM', activity: '🍛 Group dinner at a local Goan restaurant — welcome night, stories & new friendships begin' },
        ]
      },
      {
        day: 'Day 2 — Free Roam', label: 'Your Scooty. Your Choice. Your Goa.', iconKey: 'Coffee', color: 'bg-emerald-500',
        timeline: [
          { time: '08:00 AM', activity: '🌅 Morning walk along Palolem Beach — barefoot on the sand before the crowd arrives' },
          { time: '09:00 AM', activity: '🍳 Breakfast at hotel — then it\'s entirely your day. No fixed plan, no group schedule.' },
          { time: '10:00 AM', activity: '🛵 Ride out — choose your own Goa for the day:' },
          { time: '⛪ Culture Trail', activity: 'Basilica of Bom Jesus (UNESCO, 400 yr old) → Sé Cathedral (largest church in Asia) → Fontainhas Latin Quarter (colourful Portuguese lanes & cafes) → Goa State Museum' },
          { time: '🏖️ Beach Hopper', activity: 'Agonda Beach (quietest & most pristine) → Betul Beach (hidden fishing village, almost no tourists) → Cabo De Rama ruins → Cola Lagoon for a sunset dip' },
          { time: '🌿 Nature & Chill', activity: 'Dudhsagar Waterfalls jeep safari → Spice plantation walk → local cashew wine tasting → back for a hammock nap at Palolem' },
          { time: '☕ Cafe & Wander', activity: 'Panaji old town walk → lunch at a local Goan family restaurant → Mandovi River ferry → rooftop cafe with river views' },
          { time: '08:00 PM', activity: '🍛 Group dinner — everyone shares where their scooty took them. Best story of the day wins bragging rights 🗺️' },
        ]
      },
      {
        day: 'Day 3 — North Goa', label: 'Forts, Flea Markets & Famous Beaches', iconKey: 'Waves', color: 'bg-blue-500',
        timeline: [
          { time: '08:30 AM', activity: '🍳 Breakfast & hotel checkout — scooties loaded, heading north' },
          { time: '10:00 AM', activity: '🏖️ Calangute & Baga Beach — North Goa\'s most famous stretch. Swim, parasailing & jet ski (paid on spot).' },
          { time: '12:00 PM', activity: '🍽️ Lunch at a famous Baga beach shack — Britto\'s or Tito\'s lane for the full vibe' },
          { time: '01:30 PM', activity: '🏖️ Anjuna Beach — rocky cliffs, turquoise water & the iconic flea market backdrop' },
          { time: '02:30 PM', activity: '🛺 Anjuna Flea Market — Goa\'s most famous market. Boho jewellery, tie-dye clothes, spices, cashews & street food.' },
          { time: '04:00 PM', activity: '🏖️ Vagator Beach & Little Vagator — dramatic red cliffs dropping into clear blue water. Hidden & beautiful.' },
          { time: '05:00 PM', activity: '🏰 Chapora Fort — the iconic "Dil Chahta Hai" fort. 360° views of Vagator beach & the Arabian Sea. Best sunset in North Goa.' },
          { time: '07:00 PM', activity: '☕ Cafe hopping in Assagao/Mapusa — visit Gunpowder, Bhatti Village or The Bougainvillea. Artsy, quiet & very Goa.' },
          { time: '09:00 PM', activity: '🥂 Last night celebration dinner — bonfire stories, group photos & goodbye toasts 🎉' },
        ]
      },
      {
        day: 'Day 4 — Farewell', label: 'Last Sunrise, Hidden Beach & Departure', iconKey: 'Sunset', color: 'bg-orange-400',
        timeline: [
          { time: '06:30 AM', activity: '🌅 Optional early sunrise ride to Morjim Beach or Arambol — North Goa\'s quietest & most beautiful morning beaches' },
          { time: '08:30 AM', activity: '🍳 Breakfast & final checkout — pack memories, not just bags' },
          { time: '10:00 AM', activity: '📸 Final group photo stop & scooty return' },
          { time: '11:00 AM', activity: '🏖️ Quick last stop — Sinquerim Beach or Fort Aguada ruins (16th century Portuguese sea fort, very photogenic)' },
          { time: '12:30 PM', activity: '🍽️ Farewell Goan thali lunch — the real one, at a local family restaurant' },
          { time: '02:00 PM', activity: '🚂 Transfer to Madgaon / Vasco da Gama railway station — board the return sleeper train' },
          { time: 'Night',    activity: '💤 Overnight train back home — fall asleep with Goa still in your heart ❤️' },
        ]
      }
    ],
    photos: [
      'https://images.pexels.com/photos/457882/pexels-photo-457882.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/962464/pexels-photo-962464.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/994605/pexels-photo-994605.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1078983/pexels-photo-1078983.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/3601425/pexels-photo-3601425.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/2387873/pexels-photo-2387873.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    meetingPoint: {
      title: 'Departure & Meeting Point',
      lines: [
        { bold: 'Departure Cities:', text: 'Ahmedabad · Rajkot · Bhavnagar · Surat · Vadodara' },
        { bold: 'Mode of Travel:',   text: 'Sleeper Train (overnight) — comfortable and affordable' },
      ],
      note: "📍 Exact meeting point & train details shared on WhatsApp group after booking confirmation. We'll confirm 48 hours before departure.",
    },
    whatToCarry: [
      { emoji: '🪪', text: 'Government photo ID (Aadhaar / Passport)' },
      { emoji: '👙', text: 'Swimwear & light beach clothes' },
      { emoji: '🧴', text: 'Sunscreen, sunglasses & hat' },
      { emoji: '👟', text: 'Comfortable footwear & flip flops' },
      { emoji: '💊', text: 'Personal medicines if any' },
      { emoji: '🔋', text: 'Power bank & phone charger' },
      { emoji: '💵', text: 'Cash for water sports & personal expenses' },
      { emoji: '🎒', text: 'Small backpack — travel light!' },
    ],
    faqs: [
      { q: 'Can I join solo?', a: "Absolutely! Most of our travelers join solo. You'll be grouped with like-minded people from Gujarat — you won't feel out of place at all." },
      { q: 'Is it safe for solo women travelers?', a: 'Yes. We have a dedicated trip coordinator throughout and maintain a safe, respectful group environment at all times.' },
      { q: 'What train do we take?', a: 'We book a group sleeper train from your city to Madgaon (Goa). Exact train details are shared after booking confirmation.' },
      { q: 'When do I pay?', a: "No payment needed right now. Once we confirm your spot via WhatsApp/call, we'll share payment details. Full payment before departure." },
      { q: 'What if the trip gets cancelled?', a: 'If we cancel due to insufficient group size or any unforeseen reason, you get a full refund within 5–7 business days.' },
      { q: 'Are seats limited?', a: 'Yes — seats are limited per batch to keep the experience personal and high-quality. Book early to secure your spot.' },
    ],
    bookingCardInfo: [
      { label: 'Duration',      value: '3 Nights · 4 Days'  },
      { label: 'Travel',        value: '🚂 Sleeper Train'   },
      { label: 'Seats',         value: '🔥 Limited'         },
      { label: 'Pickup Cities', value: 'Ahmedabad & more'   },
      { label: 'Status',        value: '🔥 Filling Fast!'   },
    ],
    bookingCardBadge: '🔥 Early Bird',
    bookingCardSaveText: 'SAVE ₹1,000',
    bookingCardQuote: 'All inclusive: Train, stay, meals & sightseeing.',
    tagline: 'Your Scooty. Your Goa. Your Rules. 🛵',
  },
]

// Lookup helpers
export const getTripBySlug = (slug) => tripsData.find(t => t.slug === slug)
export const getOtherTrips = (slug) => tripsData.filter(t => t.slug !== slug)
